services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: crypto_db
      POSTGRES_USER: davis
      POSTGRES_PASSWORD: davis123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  metabase:
    image: metabase/metabase:latest
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  postgres_data: